MAKE = make --no-print-directory

all:
	@echo -= Compilando Programas =-
	@$(MAKE) -C Luzia all
	@$(MAKE) -C BandoDeDados all
	@$(MAKE) -C Sefudias all

ptbr:
	@$(MAKE) -C Luzia ptbr
	@$(MAKE) -C Sefudias ptbr

enus:
	@$(MAKE) -C Luzia enus
	@$(MAKE) -C Sefudias enus

clean:
	@$(MAKE) -C Luzia clean
	@$(MAKE) -C BandoDeDados clean
	@$(MAKE) -C Sefudias clean